import { withLayoutMain } from "../../layouts/LayoutMain/LayoutMain"
import Head from "next/head"
import { withCSR } from "../../HOC/with-CSR"

export const getServerSideProps = withCSR(async ctx => {
  console.log('CategoryPage getServerSideProps => ctx =>', ctx)

  const category = ctx.params.category
  console.log('category via ctx.params', category)



  return {
    props: {

    }
  }
})

const CategoryPage = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Тайтл магазина</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-10 ">
        <div className="flex">
          <aside>Фильтры</aside>
          <main>Мейн</main>
        </div>
      </div>
    </>
  )
}

export default withLayoutMain(CategoryPage)
