import Head from "next/head"
import { withLayoutMain } from "../layouts/LayoutMain/LayoutMain"
import Posts from "../components/Posts/Posts"
import { dehydrate, QueryClient, useQuery } from "react-query"
import { fetchPosts } from "../api/posts"
import Error from "../components/Error/Error"
import Cover from "../components/Cover/Cover"
import { Product } from "../inferfaces/product.interface"
import ProductsList from "../components/ProductsList/ProductsList"

const getStaticProps = async ctx => {
  console.log("getStaticProps => ctx =>", ctx)
  let isError = false
  const queryClient = new QueryClient()

  try {
    await queryClient.prefetchQuery(["posts"], fetchPosts)
  } catch (error) {
    isError = true
    // @ts-ignore
    ctx.res.statusCode = error.response.status
  }

  return {
    props: {
      //also passing down isError state to show a custom error component.
      isError,
      dehydratedState: dehydrate(queryClient)
    }
  }
}

const latestProducts: Product[] = [
  {
    id: 1,
    brand: "Найк 1",
    title: "Футболка 1",
    colors: ['Зеленый', 'Красный'],
    sizes: {
      xs: 1,
      s: 2,
      m: 3,
      l: 3,
      xl: 3,
      xxl: 0
    }
  },
  {
    id: 2,
    brand: "Найк 2",
    title: "Футболка 2 c очень длинным названием и переносом",
    colors: ['Белый', 'Чёрный'],
    sizes: {
      xs: 1,
      s: 2,
      m: 3,
      l: 3,
      xl: 3,
      xxl: 0
    }
  }
]

function Index(props) {
  // Если ошибка в базовом запроссе из getServerSideProps
  if (props.isError) return <Error />

  return (
    <>
      <Head>
        <title>Тайтл магазина</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-cyan-100">
        <section className="text-2xl text-center mb-4">
          <Cover />
        </section>
        <ProductsList products={latestProducts} />
        {/*<Posts />*/}
      </main>
    </>
  )
}

export default withLayoutMain(Index)
